### ISSUE TITLE
Search/sorting at speakers?

### ISSUE THREAD

**Issue by q587p** [arodiss/15x4#357]
How about add some search or sorting (at least in letters of alphabets) at https://15x4.org/admin/lecturers/?

Or maybe it's somewhere there and I just can not find it…

**Comment by arodiss** [comment]
Sorting is easy, search is harder.
I will add sorting

**Comment by arodiss** [comment]
Implemented in #358
Now primary sort is by name, secondary by lecture count (previously was inverse)
